zf:
  build: .
  dockerfile: Dockerfile
  ports:
    - "8080:80"
  volumes:
    - .:/var/www
  links:
    - db

db:
  image: mysql:5.7
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: myDb
    MYSQL_USER: user
    MYSQL_PASSWORD: test
    MYSQL_ROOT_PASSWORD: test
  volumes:
    - /var/lib/mysql

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - db:db
  ports:
    - 8000:80
  environment:
    MYSQL_USER: user
    MYSQL_PASSWORD: test
    MYSQL_ROOT_PASSWORD: test