<h1>Listagem de usuários</h1>

<table>



    <thead>

        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Options</th>
        </tr>
    </thead>

    <tbody>

<!--        # pegar os dados do banco de dados e mostrar aqui na tabela-->
<!--        # dados falso-->

    <tr>
        <td>0</td>
        <td>Abner</td>
        <td><button>Show</button></td>
        <td><button>Edit</button></td>
        <td><button>Delete</button></td>
    </tr>

<tr>
    <td>0</td>
    <td>Abner</td>
    <td><button>Show</button></td>
    <td><button>Edit</button></td>
    <td><button>Delete</button></td>
</tr>

<tr>
    <td>0</td>
    <td>Abner</td>
    <td><button>Show</button></td>
    <td><button>Edit</button></td>
    <td><button>Delete</button></td>
</tr>

<tr>
    <td>0</td>
    <td>Abner</td>
    <td><button>Show</button></td>
    <td><button>Edit</button></td>
    <td><button>Delete</button></td>
</tr>
    </tbody>
</table>