<h1>All users</h1>


<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" id="btnAdd">Add</button>

<table class="table">

    <thead>
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Options</th>
    </tr>
    </thead>

    <tbody id="tableList">
    </tbody>
</table>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="modalBtnSave">Save changes</button>
            </div>
        </div>
    </div>
</div>

<?php $this->headScript()->appendFile('/js/manager/users.js'); ?>
