<h1>All users</h1>

<table class="table">

    <thead>
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Options</th>
    </tr>
    </thead>

    <tbody>

    <?php foreach ($users as $user): ?>
    <tr>
        <td><?= $user->getIdUser()?></td>
        <td><?= $user->getName()?></td>
        <td><button class="btn btn-action" data-name="btnShow" data-id="<?= $user->getIdUser()?>" >Show</button><td>
        <td><button class="btn btn-action" data-name="btnEdit" data-id="<?= $user->getIdUser()?>" >Edit</button><td>
        <td><button class="btn btn-action" data-name="btnDelete" data-id="<?= $user->getIdUser()?>" >Delete</button><td>
    </tr>
    <?php endforeach; ?>

    </tbody>
</table>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
    Launch demo modal
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

<script>

    $(document).ready(function () {

        var $modal = $('#myModal');

        function onBtnShow(idUser) {


        }

        function onBtnEdit(idUser) {

        }

        function onBtnDelete(idUser) {

        }


        $('.btn-action').on('click', function(e) {

            e.stopPropagation();

            var dataName = $(this).data('name');
            var idUser = $(this).data('id');

            $modal.modal('show');

            if (dataName == 'btnShow') {

                onBtnShow(idUser);
            } else if (dataName == 'btnEdit') {

                onBtnEdit(idUser);
            } else if (dataName == 'btnDelete') {

                onBtnDelete(idUser);
            }



            console.log();
        });
    });

</script>